// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: prototypes/event.proto

package prototypes // import "github.com/linkai-io/am/protocservices/prototypes"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventData struct {
	NotificationID       int64    `protobuf:"varint,1,opt,name=NotificationID,proto3" json:"NotificationID,omitempty"`
	OrgID                int32    `protobuf:"varint,2,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	GroupID              int32    `protobuf:"varint,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	TypeID               int32    `protobuf:"varint,4,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	EventTimestamp       int64    `protobuf:"varint,5,opt,name=EventTimestamp,proto3" json:"EventTimestamp,omitempty"`
	Data                 []string `protobuf:"bytes,6,rep,name=Data" json:"Data,omitempty"`
	Read                 bool     `protobuf:"varint,7,opt,name=Read,proto3" json:"Read,omitempty"`
	JsonData             string   `protobuf:"bytes,8,opt,name=JsonData,proto3" json:"JsonData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventData) Reset()         { *m = EventData{} }
func (m *EventData) String() string { return proto.CompactTextString(m) }
func (*EventData) ProtoMessage()    {}
func (*EventData) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_9f03ce1471dbf6e2, []int{0}
}
func (m *EventData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *EventData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventData.Merge(dst, src)
}
func (m *EventData) XXX_Size() int {
	return m.Size()
}
func (m *EventData) XXX_DiscardUnknown() {
	xxx_messageInfo_EventData.DiscardUnknown(m)
}

var xxx_messageInfo_EventData proto.InternalMessageInfo

func (m *EventData) GetNotificationID() int64 {
	if m != nil {
		return m.NotificationID
	}
	return 0
}

func (m *EventData) GetOrgID() int32 {
	if m != nil {
		return m.OrgID
	}
	return 0
}

func (m *EventData) GetGroupID() int32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *EventData) GetTypeID() int32 {
	if m != nil {
		return m.TypeID
	}
	return 0
}

func (m *EventData) GetEventTimestamp() int64 {
	if m != nil {
		return m.EventTimestamp
	}
	return 0
}

func (m *EventData) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EventData) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *EventData) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

type EventSubscriptions struct {
	TypeID               int32    `protobuf:"varint,1,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	SubscribedTimestamp  int64    `protobuf:"varint,2,opt,name=SubscribedTimestamp,proto3" json:"SubscribedTimestamp,omitempty"`
	Subscribed           bool     `protobuf:"varint,3,opt,name=Subscribed,proto3" json:"Subscribed,omitempty"`
	WebhookVersion       string   `protobuf:"bytes,4,opt,name=WebhookVersion,proto3" json:"WebhookVersion,omitempty"`
	WebhookEnabled       bool     `protobuf:"varint,5,opt,name=WebhookEnabled,proto3" json:"WebhookEnabled,omitempty"`
	WebhookURL           string   `protobuf:"bytes,6,opt,name=WebhookURL,proto3" json:"WebhookURL,omitempty"`
	WebhookType          string   `protobuf:"bytes,7,opt,name=WebhookType,proto3" json:"WebhookType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventSubscriptions) Reset()         { *m = EventSubscriptions{} }
func (m *EventSubscriptions) String() string { return proto.CompactTextString(m) }
func (*EventSubscriptions) ProtoMessage()    {}
func (*EventSubscriptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_9f03ce1471dbf6e2, []int{1}
}
func (m *EventSubscriptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSubscriptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSubscriptions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *EventSubscriptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSubscriptions.Merge(dst, src)
}
func (m *EventSubscriptions) XXX_Size() int {
	return m.Size()
}
func (m *EventSubscriptions) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSubscriptions.DiscardUnknown(m)
}

var xxx_messageInfo_EventSubscriptions proto.InternalMessageInfo

func (m *EventSubscriptions) GetTypeID() int32 {
	if m != nil {
		return m.TypeID
	}
	return 0
}

func (m *EventSubscriptions) GetSubscribedTimestamp() int64 {
	if m != nil {
		return m.SubscribedTimestamp
	}
	return 0
}

func (m *EventSubscriptions) GetSubscribed() bool {
	if m != nil {
		return m.Subscribed
	}
	return false
}

func (m *EventSubscriptions) GetWebhookVersion() string {
	if m != nil {
		return m.WebhookVersion
	}
	return ""
}

func (m *EventSubscriptions) GetWebhookEnabled() bool {
	if m != nil {
		return m.WebhookEnabled
	}
	return false
}

func (m *EventSubscriptions) GetWebhookURL() string {
	if m != nil {
		return m.WebhookURL
	}
	return ""
}

func (m *EventSubscriptions) GetWebhookType() string {
	if m != nil {
		return m.WebhookType
	}
	return ""
}

type UserEventSettings struct {
	WeeklyReportSendDay  int32                 `protobuf:"varint,1,opt,name=WeeklyReportSendDay,proto3" json:"WeeklyReportSendDay,omitempty"`
	ShouldWeeklyEmail    bool                  `protobuf:"varint,2,opt,name=ShouldWeeklyEmail,proto3" json:"ShouldWeeklyEmail,omitempty"`
	DailyReportSendHour  int32                 `protobuf:"varint,3,opt,name=DailyReportSendHour,proto3" json:"DailyReportSendHour,omitempty"`
	ShouldDailyEmail     bool                  `protobuf:"varint,4,opt,name=ShouldDailyEmail,proto3" json:"ShouldDailyEmail,omitempty"`
	UserTimezone         string                `protobuf:"bytes,5,opt,name=UserTimezone,proto3" json:"UserTimezone,omitempty"`
	Subscriptions        []*EventSubscriptions `protobuf:"bytes,6,rep,name=Subscriptions" json:"Subscriptions,omitempty"`
	WebhookCurrentKey    string                `protobuf:"bytes,7,opt,name=WebhookCurrentKey,proto3" json:"WebhookCurrentKey,omitempty"`
	WebhookPreviousKey   string                `protobuf:"bytes,8,opt,name=WebhookPreviousKey,proto3" json:"WebhookPreviousKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserEventSettings) Reset()         { *m = UserEventSettings{} }
func (m *UserEventSettings) String() string { return proto.CompactTextString(m) }
func (*UserEventSettings) ProtoMessage()    {}
func (*UserEventSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_9f03ce1471dbf6e2, []int{2}
}
func (m *UserEventSettings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserEventSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserEventSettings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *UserEventSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEventSettings.Merge(dst, src)
}
func (m *UserEventSettings) XXX_Size() int {
	return m.Size()
}
func (m *UserEventSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEventSettings.DiscardUnknown(m)
}

var xxx_messageInfo_UserEventSettings proto.InternalMessageInfo

func (m *UserEventSettings) GetWeeklyReportSendDay() int32 {
	if m != nil {
		return m.WeeklyReportSendDay
	}
	return 0
}

func (m *UserEventSettings) GetShouldWeeklyEmail() bool {
	if m != nil {
		return m.ShouldWeeklyEmail
	}
	return false
}

func (m *UserEventSettings) GetDailyReportSendHour() int32 {
	if m != nil {
		return m.DailyReportSendHour
	}
	return 0
}

func (m *UserEventSettings) GetShouldDailyEmail() bool {
	if m != nil {
		return m.ShouldDailyEmail
	}
	return false
}

func (m *UserEventSettings) GetUserTimezone() string {
	if m != nil {
		return m.UserTimezone
	}
	return ""
}

func (m *UserEventSettings) GetSubscriptions() []*EventSubscriptions {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

func (m *UserEventSettings) GetWebhookCurrentKey() string {
	if m != nil {
		return m.WebhookCurrentKey
	}
	return ""
}

func (m *UserEventSettings) GetWebhookPreviousKey() string {
	if m != nil {
		return m.WebhookPreviousKey
	}
	return ""
}

type EventFilter struct {
	Start                int64       `protobuf:"varint,1,opt,name=Start,proto3" json:"Start,omitempty"`
	Limit                int32       `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Filters              *FilterType `protobuf:"bytes,3,opt,name=Filters" json:"Filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EventFilter) Reset()         { *m = EventFilter{} }
func (m *EventFilter) String() string { return proto.CompactTextString(m) }
func (*EventFilter) ProtoMessage()    {}
func (*EventFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_9f03ce1471dbf6e2, []int{3}
}
func (m *EventFilter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventFilter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *EventFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventFilter.Merge(dst, src)
}
func (m *EventFilter) XXX_Size() int {
	return m.Size()
}
func (m *EventFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EventFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EventFilter proto.InternalMessageInfo

func (m *EventFilter) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *EventFilter) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *EventFilter) GetFilters() *FilterType {
	if m != nil {
		return m.Filters
	}
	return nil
}

func init() {
	proto.RegisterType((*EventData)(nil), "EventData")
	proto.RegisterType((*EventSubscriptions)(nil), "EventSubscriptions")
	proto.RegisterType((*UserEventSettings)(nil), "UserEventSettings")
	proto.RegisterType((*EventFilter)(nil), "EventFilter")
}
func (m *EventData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventData) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NotificationID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.NotificationID))
	}
	if m.OrgID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.OrgID))
	}
	if m.GroupID != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.GroupID))
	}
	if m.TypeID != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.TypeID))
	}
	if m.EventTimestamp != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.EventTimestamp))
	}
	if len(m.Data) > 0 {
		for _, s := range m.Data {
			dAtA[i] = 0x32
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if m.Read {
		dAtA[i] = 0x38
		i++
		if m.Read {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.JsonData) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.JsonData)))
		i += copy(dAtA[i:], m.JsonData)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *EventSubscriptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSubscriptions) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TypeID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.TypeID))
	}
	if m.SubscribedTimestamp != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.SubscribedTimestamp))
	}
	if m.Subscribed {
		dAtA[i] = 0x18
		i++
		if m.Subscribed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.WebhookVersion) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.WebhookVersion)))
		i += copy(dAtA[i:], m.WebhookVersion)
	}
	if m.WebhookEnabled {
		dAtA[i] = 0x28
		i++
		if m.WebhookEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.WebhookURL) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.WebhookURL)))
		i += copy(dAtA[i:], m.WebhookURL)
	}
	if len(m.WebhookType) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.WebhookType)))
		i += copy(dAtA[i:], m.WebhookType)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UserEventSettings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserEventSettings) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.WeeklyReportSendDay != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.WeeklyReportSendDay))
	}
	if m.ShouldWeeklyEmail {
		dAtA[i] = 0x10
		i++
		if m.ShouldWeeklyEmail {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.DailyReportSendHour != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.DailyReportSendHour))
	}
	if m.ShouldDailyEmail {
		dAtA[i] = 0x20
		i++
		if m.ShouldDailyEmail {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.UserTimezone) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.UserTimezone)))
		i += copy(dAtA[i:], m.UserTimezone)
	}
	if len(m.Subscriptions) > 0 {
		for _, msg := range m.Subscriptions {
			dAtA[i] = 0x32
			i++
			i = encodeVarintEvent(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.WebhookCurrentKey) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.WebhookCurrentKey)))
		i += copy(dAtA[i:], m.WebhookCurrentKey)
	}
	if len(m.WebhookPreviousKey) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.WebhookPreviousKey)))
		i += copy(dAtA[i:], m.WebhookPreviousKey)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *EventFilter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventFilter) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Start != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.Start))
	}
	if m.Limit != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.Limit))
	}
	if m.Filters != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.Filters.Size()))
		n1, err := m.Filters.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *EventData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NotificationID != 0 {
		n += 1 + sovEvent(uint64(m.NotificationID))
	}
	if m.OrgID != 0 {
		n += 1 + sovEvent(uint64(m.OrgID))
	}
	if m.GroupID != 0 {
		n += 1 + sovEvent(uint64(m.GroupID))
	}
	if m.TypeID != 0 {
		n += 1 + sovEvent(uint64(m.TypeID))
	}
	if m.EventTimestamp != 0 {
		n += 1 + sovEvent(uint64(m.EventTimestamp))
	}
	if len(m.Data) > 0 {
		for _, s := range m.Data {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if m.Read {
		n += 2
	}
	l = len(m.JsonData)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EventSubscriptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TypeID != 0 {
		n += 1 + sovEvent(uint64(m.TypeID))
	}
	if m.SubscribedTimestamp != 0 {
		n += 1 + sovEvent(uint64(m.SubscribedTimestamp))
	}
	if m.Subscribed {
		n += 2
	}
	l = len(m.WebhookVersion)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.WebhookEnabled {
		n += 2
	}
	l = len(m.WebhookURL)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.WebhookType)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UserEventSettings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WeeklyReportSendDay != 0 {
		n += 1 + sovEvent(uint64(m.WeeklyReportSendDay))
	}
	if m.ShouldWeeklyEmail {
		n += 2
	}
	if m.DailyReportSendHour != 0 {
		n += 1 + sovEvent(uint64(m.DailyReportSendHour))
	}
	if m.ShouldDailyEmail {
		n += 2
	}
	l = len(m.UserTimezone)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if len(m.Subscriptions) > 0 {
		for _, e := range m.Subscriptions {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	l = len(m.WebhookCurrentKey)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.WebhookPreviousKey)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EventFilter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Start != 0 {
		n += 1 + sovEvent(uint64(m.Start))
	}
	if m.Limit != 0 {
		n += 1 + sovEvent(uint64(m.Limit))
	}
	if m.Filters != nil {
		l = m.Filters.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovEvent(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NotificationID", wireType)
			}
			m.NotificationID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NotificationID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgID", wireType)
			}
			m.OrgID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrgID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupID", wireType)
			}
			m.GroupID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeID", wireType)
			}
			m.TypeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TypeID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventTimestamp", wireType)
			}
			m.EventTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventTimestamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Read", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Read = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JsonData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JsonData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventSubscriptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSubscriptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSubscriptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeID", wireType)
			}
			m.TypeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TypeID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscribedTimestamp", wireType)
			}
			m.SubscribedTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscribedTimestamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subscribed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Subscribed = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebhookVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebhookVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebhookEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WebhookEnabled = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebhookURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebhookURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebhookType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebhookType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserEventSettings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserEventSettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserEventSettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeeklyReportSendDay", wireType)
			}
			m.WeeklyReportSendDay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WeeklyReportSendDay |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShouldWeeklyEmail", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ShouldWeeklyEmail = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyReportSendHour", wireType)
			}
			m.DailyReportSendHour = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DailyReportSendHour |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShouldDailyEmail", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ShouldDailyEmail = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserTimezone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserTimezone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subscriptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subscriptions = append(m.Subscriptions, &EventSubscriptions{})
			if err := m.Subscriptions[len(m.Subscriptions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebhookCurrentKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebhookCurrentKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebhookPreviousKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebhookPreviousKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventFilter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventFilter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventFilter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Filters == nil {
				m.Filters = &FilterType{}
			}
			if err := m.Filters.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEvent
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEvent(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEvent = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("prototypes/event.proto", fileDescriptor_event_9f03ce1471dbf6e2) }

var fileDescriptor_event_9f03ce1471dbf6e2 = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0x7f, 0x6e, 0xda, 0xd4, 0xde, 0xfc, 0x40, 0x74, 0x8b, 0x2a, 0xab, 0x48, 0x91, 0x15,
	0x09, 0x14, 0x21, 0x48, 0xa0, 0x9c, 0xb8, 0x52, 0x07, 0x08, 0x54, 0x80, 0x36, 0x2d, 0x95, 0x38,
	0xb1, 0x4e, 0xa6, 0xc9, 0x2a, 0xb6, 0xd7, 0xda, 0x5d, 0x47, 0x0a, 0x0f, 0x81, 0x38, 0xf2, 0x48,
	0x1c, 0x79, 0x04, 0x14, 0x0e, 0xbc, 0x06, 0xda, 0xb1, 0x43, 0x9c, 0x3f, 0xb7, 0x9d, 0xcf, 0x77,
	0x32, 0x3b, 0xf3, 0xcd, 0xac, 0xc9, 0x49, 0xa6, 0xa4, 0x91, 0x66, 0x9e, 0x81, 0xee, 0xc2, 0x0c,
	0x52, 0xd3, 0x41, 0x70, 0x7a, 0xaf, 0xc2, 0x6f, 0x44, 0x6c, 0x40, 0xd9, 0x73, 0x21, 0xb6, 0xfe,
	0x38, 0xc4, 0xeb, 0xd9, 0xe4, 0x90, 0x1b, 0x4e, 0x1f, 0x90, 0xdb, 0xef, 0xa4, 0x11, 0x37, 0x62,
	0xc8, 0x8d, 0x90, 0x69, 0x3f, 0xf4, 0x9d, 0xc0, 0x69, 0xd7, 0xd8, 0x06, 0xa5, 0x77, 0xc9, 0xc1,
	0x7b, 0x35, 0xee, 0x87, 0xfe, 0x5e, 0xe0, 0xb4, 0x0f, 0x58, 0x11, 0x50, 0x9f, 0x1c, 0xbe, 0x52,
	0x32, 0xcf, 0xfa, 0xa1, 0x5f, 0x43, 0xbe, 0x0c, 0xe9, 0x09, 0xa9, 0x5f, 0xce, 0x33, 0xe8, 0x87,
	0xfe, 0x3e, 0x0a, 0x65, 0x64, 0xef, 0xc3, 0xcb, 0x2f, 0x45, 0x02, 0xda, 0xf0, 0x24, 0xf3, 0x0f,
	0x8a, 0xfb, 0xd6, 0x29, 0xa5, 0x64, 0xdf, 0xf6, 0xe7, 0xd7, 0x83, 0x5a, 0xdb, 0x63, 0x78, 0xb6,
	0x8c, 0x01, 0x1f, 0xf9, 0x87, 0x81, 0xd3, 0x76, 0x19, 0x9e, 0xe9, 0x29, 0x71, 0xdf, 0x68, 0x99,
	0x62, 0xae, 0x1b, 0x38, 0x6d, 0x8f, 0xfd, 0x8b, 0x5b, 0xdf, 0xf6, 0x08, 0xc5, 0xb2, 0x83, 0x3c,
	0xd2, 0x43, 0x25, 0x32, 0x3b, 0x8b, 0xae, 0xb4, 0xe6, 0xac, 0xb5, 0xf6, 0x84, 0x1c, 0x97, 0x89,
	0x11, 0x8c, 0x56, 0xfd, 0xed, 0x61, 0x7f, 0xbb, 0x24, 0xda, 0x24, 0x64, 0x85, 0xd1, 0x01, 0x97,
	0x55, 0x88, 0x1d, 0xf6, 0x1a, 0xa2, 0x89, 0x94, 0xd3, 0x8f, 0xa0, 0xb4, 0x90, 0x29, 0x9a, 0xe1,
	0xb1, 0x0d, 0x5a, 0xc9, 0xeb, 0xa5, 0x3c, 0x8a, 0x61, 0x84, 0xa6, 0xb8, 0x6c, 0x83, 0xda, 0xfb,
	0x4a, 0x72, 0xc5, 0x2e, 0xfc, 0x3a, 0xd6, 0xaa, 0x10, 0x1a, 0x90, 0x46, 0x19, 0xd9, 0x91, 0xd0,
	0x27, 0x8f, 0x55, 0x51, 0xeb, 0x6b, 0x8d, 0x1c, 0x5d, 0x69, 0x50, 0x85, 0x2d, 0x60, 0x8c, 0x48,
	0xc7, 0xda, 0x4e, 0x7e, 0x0d, 0x30, 0x8d, 0xe7, 0x0c, 0x32, 0xa9, 0xcc, 0x00, 0xd2, 0x51, 0xc8,
	0xe7, 0xa5, 0x3d, 0xbb, 0x24, 0xfa, 0x88, 0x1c, 0x0d, 0x26, 0x32, 0x8f, 0x47, 0x85, 0xd8, 0x4b,
	0xb8, 0x88, 0xd1, 0x29, 0x97, 0x6d, 0x0b, 0xb6, 0x7e, 0xc8, 0x45, 0xb5, 0xc6, 0x6b, 0x99, 0xab,
	0x72, 0x65, 0x76, 0x49, 0xf4, 0x21, 0xb9, 0x53, 0x94, 0x41, 0xb1, 0x28, 0xbf, 0x8f, 0xe5, 0xb7,
	0x38, 0x6d, 0x91, 0xff, 0xed, 0x48, 0xf6, 0x6f, 0xf9, 0x22, 0x53, 0x40, 0xef, 0x3c, 0xb6, 0xc6,
	0xe8, 0x73, 0x72, 0x6b, 0x6d, 0x09, 0x70, 0xaf, 0x1a, 0x67, 0xc7, 0x9d, 0xed, 0xfd, 0x60, 0xeb,
	0x99, 0x76, 0xd4, 0xd2, 0xc1, 0xf3, 0x5c, 0x29, 0x48, 0xcd, 0x5b, 0x98, 0x97, 0xd6, 0x6e, 0x0b,
	0xb4, 0x43, 0x68, 0x09, 0x3f, 0x28, 0x98, 0x09, 0x99, 0x6b, 0x9b, 0x5e, 0x6c, 0xe6, 0x0e, 0xa5,
	0xf5, 0x99, 0x34, 0xb0, 0x85, 0x97, 0xf8, 0x4c, 0xed, 0x33, 0x1b, 0x18, 0xae, 0x4c, 0xf9, 0x0a,
	0x8b, 0xc0, 0xd2, 0x0b, 0x91, 0x08, 0xb3, 0x7c, 0x7c, 0x18, 0xd0, 0xfb, 0xe4, 0xb0, 0xf8, 0x95,
	0x46, 0x27, 0x1b, 0x67, 0x8d, 0x4e, 0x11, 0xdb, 0x7f, 0x9a, 0x2d, 0xb5, 0x17, 0xe7, 0x3f, 0x16,
	0x4d, 0xe7, 0xe7, 0xa2, 0xe9, 0xfc, 0x5a, 0x34, 0x9d, 0xef, 0xbf, 0x9b, 0xff, 0x7d, 0x7a, 0x3a,
	0x16, 0x66, 0x92, 0x47, 0x9d, 0xa1, 0x4c, 0xba, 0xb1, 0x48, 0xa7, 0x5c, 0x3c, 0x16, 0xb2, 0xcb,
	0x93, 0x2e, 0x7e, 0x20, 0x86, 0x1a, 0xd4, 0x4c, 0x0c, 0x41, 0x77, 0x57, 0x5f, 0x91, 0xa8, 0x8e,
	0xe7, 0x67, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xda, 0x71, 0xf8, 0x72, 0x04, 0x00, 0x00,
}
